app/models/users.py
from flask import current_app, flash
from werkzeug.security import generate_password_hash, check_password_hash
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from itsdangerous import BadSignature,SignatureExpired
from app.extensions import db, login_manager
from flask_login import UserMixin

from .post import Post


class User(UserMixin,db.Model):
    __tablename__='users'
    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(32),nullable=False,unique=True)
    password_hash = db.Column(db.String(128),nullable=False)
    email = db.Column(db.String(64),nullable=False,unique=True)
    #是否激活
    confirm = db.Column(db.Boolean,default=False)

    # 头像
    icon = db.Column(db.String(64), default='default.jpg')
    # 在另一模型中添加一个反向引用
    # 参数1：关联的模型名
    # backref：在关联的模型中动态添加的字段
    # 加载方式：dynamic，不加载，但是提供记录的查询
    # 若使用一对一，添加uselist=Flase
    posts = db.relationship('Post', backref='user', lazy=True)

    # 收藏
    # secondary：指定关系表
    favorites = db.relationship('Post', secondary='collections',
                                backref=db.backref('users', lazy='dynamic'),
                                lazy='dynamic')
    # focus = db.relationship('User', secondary='focus',
    #                             backref=db.backref('focusid', lazy='dynamic'),
    #                             lazy='dynamic')
    #

    def __repr__(self):
        return self.username

    # 密码字段保护
    @property
    def password(self):
        raise AttributeError('密码是不可读属性')

    # 设置密码，加密存储
    @password.setter
    def password(self, password):
        #相当于执行  user.password_hash=password
        self.password_hash = generate_password_hash(password)

        # 生成激活的token
    def generate_activate_token(self):
        # 创建用于生成token的类，需要传递秘钥和有效期expires_in默认=3600,expires_in=60
        s = Serializer(current_app.config['SECRET_KEY'])
        # 生成包含有效信息(必须是字典数据)的token字符串
        return s.dumps({'id': self.id})

    #生成任意的token
    @staticmethod
    def generate_token(dict):
        s = Serializer(current_app.config['SECRET_KEY'])
        # 生成包含有效信息(必须是字典数据)的token字符串
        return s.dumps(dict)
    #检查任意token是否有效,返回真实词典数据
    @staticmethod
    def check_token(token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except SignatureExpired:
            flash('邮件已过期')
            return False
        except BadSignature:
            flash('无效的验证邮箱')
            return False
        return data

    # 账户激活，因为激活时还不知道是哪个用户
    @staticmethod
    def check_activate_token(token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
            print(data)
        except SignatureExpired:
            flash('激活邮件已过期')
            return False
        except BadSignature:
            flash('无效的激活')
            return False
        user = User.query.get(data.get('id'))
        print(user)
        if not user:
            flash('激活的账户不存在')
            return False
        if not user.confirm:  # 没有激活才需要激活
            user.confirm = True
            db.session.add(user)
        return True

    # 密码的校验
    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    #判断是否收藏
    def is_favorites(self,pid):
        #获取微博对象
        post = Post.query.get(pid)
        #判断微博是否在用户收藏列表中
        if post in self.favorites:
            #说明已经收藏
            return True
        else:
            return False

    # 收藏指定帖子
    def add_favorite(self, pid):
        p = Post.query.get(pid)
        self.favorites.append(p)

    # 取消收藏指定帖子
    def cancel_favorite(self, pid):
        p = Post.query.get(pid)
        self.favorites.remove(p)

    # # 判断是否收藏
    # def is_focus(self, uid):
    #     # 获取用户对象
    #     user =User.query.get(uid)
    #     # 判断是否关注对方
    #     if user in self.focus:
    #
    #         return True
    #     else:
    #         return False
    # #关注对方
    # def add_focus(self, uid):
    #     user = User.query.get(uid)
    #     self.favorites.append(user)
    #
    #
    # #取消关注
    # def cancel_focus(self, uid):
    #     user = User.query.get(uid)
    #     self.favorites.remove(user)

# 登录认证的回调，写在user model中
@login_manager.user_loader
def load_user(uid):
    return User.query.get(int(uid))

app/forms/users.py
from flask_login import current_user
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField, FileField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_wtf.file import FileField, FileAllowed, FileRequired

from app.models import User
from app.extensions import photos


class RegisterForm(FlaskForm):
    username = StringField('用户名', validators=[DataRequired(message='请填写用户名'), Length(4, 20, message='长度在4到20个字符之间')])
    email = StringField('邮箱(务必填写正确,否则无法激活登录)', validators=[DataRequired(message='请填写邮箱'), Email(message='请填写正确的邮箱格式')])
    password = PasswordField('密码', validators=[DataRequired(message='请填写密码'), Length(8, 20, message='密码长度在8到20之间'),
                                               EqualTo('confirm', message='密码不一致')])
    confirm = PasswordField('密码确认')
    submit = SubmitField('注册')

    # 检验username是否存在
    def validate_username(self, field):
        user = User.query.filter_by(username=field.data).first()
        if user:
            raise ValidationError('用户名已存在')

    # 校验邮箱是否已存在
    def validate_email(self, field):
        user = User.query.filter_by(email=field.data).first()
        if user:
            raise ValidationError('邮箱已存在')


# 定义登录的form表单
class LoginForm(FlaskForm):
    username = StringField('用户名或邮箱', validators=[DataRequired(message='用户名不能为空')])
    password = PasswordField('密码', validators=[DataRequired(message='密码不能为空')])
    remember = BooleanField('记住我',default=True)
    submit = SubmitField('登录')


# 定义修改密码的表单
class UserPasswordForm(FlaskForm):
    oldpwd = PasswordField('原密码', validators=[DataRequired(message='原密码不能为空')])
    newpwd = PasswordField('新密码', validators=[DataRequired(message='请填写新密码'), Length(8, 20, message='密码长度在8到20之间'),
                                              EqualTo('confirm', message='密码不一致')])
    confirm = PasswordField('密码确认')
    submit = SubmitField('注册')

    # 校验原密码是否正确
    def validate_oldpwd(self, field):
        # 获取真实user对象
        user = current_user._get_current_object()
        if not user.verify_password(field.data):
            raise ValidationError('原密码错误')

    # 校验新老密码不能一致
    def validate_newpwd(self, field):
        # 获取真实user对象
        user = current_user._get_current_object()
        if user.verify_password(field.data):
            raise ValidationError('新旧密码不能一样')


# 添加头像表单
class IconForm(FlaskForm):
    icon = FileField('头像', render_kw={'class': 'btn btn-default'},
                     validators=[FileAllowed(photos, message='只能上传图片'), FileRequired(message='请先选择文件')])
    submit = SubmitField('修改')


# 填写新邮箱来修改邮箱
class EmailForm(FlaskForm):
    email = StringField('新邮箱(务必填写正确,否则无法收到修改邮件)',
                        validators=[DataRequired(message='请填写新邮箱'), Email(message='请填写正确的邮箱格式')])
    submit = SubmitField('提交')


# 用来提交用户名或邮箱来重置密码
class EUForm(FlaskForm):
    username = StringField('用户名或有效的邮箱', validators=[DataRequired(message='用户名不能为空')])
    submit = SubmitField('下一步',render_kw={'style':"float: right"})

# 用来提交验证码
class AuthCodeForm(FlaskForm):
    authcode = StringField('验证码', validators=[DataRequired(message='验证码不能为空')])
    submit = SubmitField('提交',render_kw={'style':"float: right"})


#重置密码
class ResetPwdForm(FlaskForm):
    password = PasswordField('新密码', validators=[DataRequired(message='请填写密码'), Length(8, 20, message='密码长度在8到20之间'),
                                               EqualTo('confirm', message='密码不一致')])
    confirm = PasswordField('密码确认')
    submit = SubmitField('确定',render_kw={'style':"float: right"})

app/main/views/users.py
import os

import time
from PIL import Image
from flask import Blueprint, flash, render_template, redirect, url_for, current_app, request, jsonify
from sqlalchemy import or_

from app.extensions import db
from app.forms import RegisterForm, LoginForm, UserPasswordForm, IconForm, EmailForm, EUForm, AuthCodeForm, \
    ResetPwdForm, CommentForm
from app.models import User, Post
from app.email import send_mail
from flask_login import login_user, logout_user, current_user
from app.extensions import photos

users = Blueprint('users', __name__)


@users.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, password=form.password.data,
                    email=form.email.data)
        db.session.add(user)
        db.session.commit()
        # 发激活邮件
        # 生成一个token，令牌，包含失效，包含用户信息()
        token = user.generate_activate_token()
        send_mail([user.email], '激活邮件', 'email/activate', username=user.username, token=token)
        flash('注册成功')
        return redirect(url_for('users.login'))

    return render_template('users/register.html', form=form)


# 激活
@users.route('/activate/<token>/')
def activate(token):
    if User.check_activate_token(token):
        flash('账户已激活')
        return redirect(url_for('main.pzl'))
    else:
        flash('激活失败')
        return redirect(url_for('main.pzl'))


# 用户登录
@users.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        user = User.query.filter(or_(User.username == username, User.email == username)).first()
        if not user:
            flash('用户名或密码错误')
        elif not user.confirm:
            flash('用户未被激活,请先激活在登录')
        elif not user.verify_password(form.password.data):
            flash('用户名或密码错误')
        else:
            login_user(user, remember=form.remember.data)
            flash('登录成功')
            return redirect(url_for('main.pzl', next=request.args.get('next')))
    return render_template('users/login.html', form=form)


@users.route('/logout/')
def logout():
    logout_user()
    return redirect(url_for('main.pzl'))


# 展示用户个人信息
@users.route('/profile/')
def profile():
    return render_template('users/profile.html')


@users.route('/change_password/', methods=['GET', 'POST'])
def change_password():
    form = UserPasswordForm()
    if form.validate_on_submit():
        newpwd = form.newpwd.data
        user = current_user._get_current_object()
        user.password = newpwd
        db.session.add(user)
        # 退出登录
        logout_user()
        flash('密码修改成功，请重新登录')
        return redirect(url_for('users.login'))
    return render_template('users/change_password.html', form=form)


# 生成随机的字符串
def random_string(length=32):
    import random
    import string
    base_str = string.ascii_letters + string.digits
    return ''.join(random.choice(base_str) for _ in range(length))


@users.route('/reset_password/', methods=['GET', 'POST'])
def reset_password():
    form1 = EUForm()
    global authcode
    authcode = random_string(length=6)
    if form1.validate_on_submit():
        global Uname
        username = form1.username.data
        Uname = username
        user = User.query.filter(or_(User.username == username, User.email == username)).first()
        # print(user.email)
        if user:
            send_mail([user.email], '验证码邮件', 'email/authcode', username=user.username, authcode=authcode)
            flash('验证码邮件已发送,注意查收')
            return redirect(url_for('users.reset_password2'))
        else:
            flash('请输入正确的用户名或邮箱')
    return render_template('users/reset_password.html', form1=form1)


@users.route('/reset_password2/', methods=['GET', 'POST'])
def reset_password2():
    form2 = AuthCodeForm()
    if form2.validate_on_submit():
        if authcode == form2.authcode.data:
            return redirect(url_for('users.reset_password3'))
        else:
            flash('验证码错误！')
    return render_template('users/reset_password2.html', form2=form2)


@users.route('/reset_password3/', methods=['GET', 'POST'])
def reset_password3():
    form3 = ResetPwdForm()
    user = User.query.filter(or_(User.username == Uname, User.email == Uname)).first()
    print(user)
    if form3.validate_on_submit():
        newpwd = form3.password.data
        if not user.verify_password(newpwd):
            user.password = newpwd
            db.session.add(user)
        logout_user()
        return redirect(url_for('users.reset_password4'))
    return render_template('users/reset_password3.html', form3=form3)


@users.route('/reset_password4/')
def reset_password4():
    return render_template('users/reset_password4.html')


@users.route('/edit_icon/', methods=['GET', 'POST'])
def edit_icon():
    form = IconForm()
    if form.validate_on_submit():
        # 生成随机文件名
        suffix = os.path.splitext(form.icon.data.filename)[1]
        filename = random_string() + suffix
        # 保存文件
        photos.save(form.icon.data, name=filename)

        # 拼接完整的路径名
        pathname = os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'], filename)
        # 生成缩略图
        img = Image.open(pathname)
        # 重新设置尺寸
        img.thumbnail((128, 128))
        # 重新保存
        img.save(pathname)

        # 删除原来的头像，默认的除外
        if current_user.icon != 'default.jpg':
            os.remove(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'], current_user.icon))
        # 保存修改到数据库
        current_user.icon = filename
        db.session.add(current_user)
        flash('头像修改成功')
    return render_template('users/edit_icon.html', form=form)


# 修改邮箱
@users.route('/change_email/', methods=['GET', 'POST'])
def change_email():
    form = EmailForm()
    if form.validate_on_submit():
        newemail = form.email.data
        infoDict = {'user_id': current_user.id, 'newemail': newemail}
        token = User.generate_token(infoDict)
        send_mail([newemail], '修改邮箱邮件', 'email/change_email', username=current_user.username, token=token)
        flash('邮件已发送，注意查收')
        form.email.data = ''
    return render_template('users/change_email.html', form=form)


@users.route('/success_change_email/<token>/')
def success_change_email(token):
    data = User.check_token(token)
    if data:
        user = User.query.get(data['user_id'])
        if user.email != data['newemail']:
            user.email = data['newemail']
            db.session.add(user)
        flash('邮箱修改成功,请查看个人信息')
        return redirect(url_for('main.pzl'))
    else:
        flash('邮件已失效,请重新发送')
        return redirect(url_for('users.change_email'))


# 收藏功能
@users.route('/collect/<int:pid>/')
def collect(pid):
    # 收藏逻辑
    if current_user.is_favorites(pid):
        # 已收藏，则取消收藏
        current_user.cancel_favorite(pid)
    else:
        current_user.add_favorite(pid)
    return jsonify({'result': 'ok'})

# 关注功能
@users.route('/focus/<int:uid>/')
def focus(uid):
    # # 关注逻辑
    # if current_user.is_focus(uid):
    #     # 已关注，则取消关注
    #     current_user.cancel_focus(uid)
    # else:
    #     current_user.add_focus(uid)
    return jsonify({'result': 'ok'})



# 帖子详情页有评论表单和显示评论
@users.route('/comment/<int:pid>/', methods=['GET', 'POST'])
def comment(pid):
    form = CommentForm()
    post = Post.query.get(pid)
    post.visitors += 1
    db.session.add(post)
    if form.validate_on_submit():
        # 判断用户是否登录
        if current_user.is_authenticated:
            p = Post(content=form.content.data, users_id=current_user.id, rid=pid)
            db.session.add(p)
            form.content.data = ''
            flash('评论成功')

        else:
            flash('登录后才能发布评论哦')
            return redirect(url_for('users.login'))
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.filter_by(rid=pid). \
        order_by(Post.timestamp.desc()).paginate(page, per_page=3, error_out=False)
    comments = pagination.items
    return render_template('common/comment.html', form=form, post=post, pagination=pagination, comments=comments)

#显示我发过的的微博
@users.route('/myposts/')
def myposts():
    page = request.args.get('page', 1, type=int)
    # print(current_user.posts,type(current_user.posts))
    pagination = Post.query.filter_by(rid=0,users_id=current_user.id). \
        order_by(Post.timestamp.desc()).paginate(page, per_page=3, error_out=False)
    posts = pagination.items
    return render_template('common/mypost.html',posts=posts, pagination=pagination)


#显示我收藏过得的微博
@users.route('/myfavorites/')
def myfavorites():
    page = request.args.get('page', 1, type=int)
    print(current_user.favorites,type(current_user.favorites))
    # pagination = Post.query.filter_by(rid=0, users_id=current_user.id). \
    #     order_by(Post.timestamp.desc()).paginate(page, per_page=3, error_out=False)
    pagination = current_user.favorites. \
        order_by(Post.timestamp.desc()).paginate(page, per_page=3, error_out=False)
    posts = pagination.items
    return render_template('common/myfavorites.html', posts=posts, pagination=pagination)


#展示被点击用户头像跳转到该用户的用户发的帖子和用户信息
@users.route('/udetail/<int:uid>/')
def udetail(uid):
    user=User.query.get(uid)
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.filter_by(users_id=user.id). \
        order_by(Post.timestamp.desc()).paginate(page, per_page=3, error_out=False)
    posts = pagination.items
    return render_template('common/udetail.html', user=user,posts=posts, pagination=pagination)

app/templates/users/change_email.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %} 修改邮箱 {% endblock %}

{% block page_content %}
    <h1 align="center">修改邮箱</h1>
    <hr>
    {{ wtf.quick_form(form) }}
{% endblock %}

app/templates/users/change_password.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %} 密码修改 {% endblock %}

{% block page_content %}
    <h1 align="center">修改密码</h1>
    <hr>
    {{ wtf.quick_form(form) }}
    <p style="margin-top: 10px;display: inline-block">如果忘记原密码，建议通过<a href="{{ url_for('users.reset_password') }}">找回密码</a>的方式来完成修改密码</p>
{% endblock %}

app/templates/users/edit_icon.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block title %} 修改头像 {% endblock %}

{% block page_content %}
    <h1 align="center">修改头像</h1>
    <hr>
    <img src="{{ url_for('static', filename='uploads/' + current_user.icon) }}" alt="本为头像">
    {{ wtf.quick_form(form) }}
{% endblock %}

app/templates/users/login.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %} 用户登录 {% endblock %}

{% block page_content %}
    <h1 align="center">用户登录</h1>
    <hr>
    {{ wtf.quick_form(form,button_map={'submit':'primary'}) }}
    <div>
        <div style="margin-top: 5px"><span>没有账号？<a href="{{ url_for('users.register') }}">立即注册</a></span></div>
        <div style="float: right"><span><a href="{{ url_for('users.reset_password') }}">忘记密码？</a></span></div>
    </div>
{% endblock %}

app/templates/users/profile.html
{% extends 'base.html' %}

{% block title %}用户详情{% endblock %}

{% block page_content %}
    <h1 align="center">用户详细信息</h1>
    <hr>
    <div class="form-group">
        <label for="inputUsername">用户名</label>
        <input type="text" class="form-control" id="inputUsername" value="{{ current_user.username }}" readonly>
    </div>
    <div class="form-group">
        <label for="inputEmail">邮箱</label>
        <input type="text" class="form-control" id="inputEmail" value="{{ current_user.email }}" readonly>
    </div>
{% endblock %}

app/templates/users/register.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %} 用户注册 {% endblock %}

{% block page_content %}
    <h1 align="center">用户注册</h1>
    <hr>
    {{ wtf.quick_form(form,button_map={'submit':'primary'}) }}

    <div align="center">
        <a href="{{ url_for('users.login') }}">已有账号登录</a>
    </div>
{% endblock %}

app/templates/users/reset_password.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %} 重置密码 {% endblock %}

{% block page_content %}
    <h1 align="center">重置密码</h1>
    <div align="center">
        <ul class="nav nav-pills">
            <li role="presentation" class="active"><a href="{{ url_for('users.reset_password') }}">①输入用户名或邮箱</a></li>
            <li role="presentation"><a href="#">②输入验证码</a></li>
            <li role="presentation"><a href="#">③设置密码</a></li>
            <li role="presentation"><a href="#">④完成</a></li>
        </ul>
    </div>
    <hr>
    {{ wtf.quick_form(form1,button_map={'submit':'primary'}) }}
{% endblock %}

app/templates/users/reset_password2.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %} 重置密码 {% endblock %}

{% block page_content %}
    <h1 align="center">重置密码</h1>
    <div align="center">
        <ul class="nav nav-pills">
            <li role="presentation"><a href="{{ url_for('users.reset_password') }}">①输入用户名或邮箱</a></li>
            <li role="presentation" class="active"><a href="#">②输入验证码</a></li>
            <li role="presentation"><a href="#">③设置密码</a></li>
            <li role="presentation"><a href="#">④完成</a></li>
        </ul>
    </div>
    <hr>
{#    <p>邮箱：{{ user.email }}</p>#}
    {{ wtf.quick_form(form2,action=url_for('users.reset_password2'),button_map={'submit':'primary',}) }}
{% endblock %}

app/templates/users/reset_password3.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %} 重置密码 {% endblock %}

{% block page_content %}
    <h1 align="center">重置密码</h1>
    <div align="center">
        <ul class="nav nav-pills">
            <li role="presentation"><a href="{{ url_for('users.reset_password') }}">①输入用户名或邮箱</a></li>
            <li role="presentation"><a href="#">②输入验证码</a></li>
            <li role="presentation" class="active"><a href="#">③设置密码</a></li>
            <li role="presentation"><a href="#">④完成</a></li>
        </ul>
    </div>
    <hr>
    {{ wtf.quick_form(form3,button_map={'submit':'primary'}) }}
{% endblock %}

app/templates/users/reset_password4.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %} 重置密码 {% endblock %}

{% block page_content %}
    <h1 align="center">重置密码</h1>
    <div align="center">
        <ul class="nav nav-pills">
            <li role="presentation"><a href="{{ url_for('users.reset_password') }}">①输入用户名或邮箱</a></li>
            <li role="presentation"><a href="#">②输入验证码</a></li>
            <li role="presentation"><a href="#">③设置密码</a></li>
            <li role="presentation" class="active"><a href="#">④完成</a></li>
        </ul>
    </div>
    <hr>
    <h2>密码重置完成,<a href="{{ url_for('users.login') }}">马上登录</a></h2>
{% endblock %}